version: v0.13.0

dsn: postgres://kratos:kratos_dev@postgres-kratos:5432/kratos?sslmode=disable

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  allowed_return_urls:
    - http://127.0.0.1:4455
    - http://localhost:4455

  methods:
    password:
      enabled: true
    code:
      enabled: true
    totp:
      config:
        issuer: Uber-like
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m

    registration:
      ui_url: http://127.0.0.1:4455/registration
      lifespan: 10m

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      use: code

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
      use: code

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - local-only-cookie-secret-change-me
  cipher:
    - local-only-cipher-secret-32chars

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 10

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtp://mailpit:1025/?disable_starttls=true
    from_address: no-reply@uber-like.local
    from_name: Uber-like

feature_flags:
  use_continue_with_transitions: true
